const periodicTableData = [
    // Period 1
    { symbol: "H", name: "Hydrogène", number: 1, atomic_mass: 1.008, category: "Non-métal", group: 1, period: 1, color: "#FFB2B2" },
    { symbol: "He", name: "Hélium", number: 2, atomic_mass: 4.0026, category: "Gaz noble", group: 18, period: 1, color: "#B2B2FF" },
    // Period 2
    { symbol: "Li", name: "Lithium", number: 3, atomic_mass: 6.94, category: "Métal alcalin", group: 1, period: 2, color: "#FFCC99" },
    { symbol: "Be", name: "Béryllium", number: 4, atomic_mass: 9.0122, category: "Métal alcalino-terreux", group: 2, period: 2, color: "#D2FF99" },
    { symbol: "B", name: "Bore", number: 5, atomic_mass: 10.81, category: "Métalloïde", group: 13, period: 2, color: "#FFD2B2" },
    { symbol: "C", name: "Carbone", number: 6, atomic_mass: 12.011, category: "Non-métal", group: 14, period: 2, color: "#FFB2B2" },
    { symbol: "N", name: "Azote", number: 7, atomic_mass: 14.007, category: "Non-métal", group: 15, period: 2, color: "#FFB2B2" },
    { symbol: "O", name: "Oxygène", number: 8, atomic_mass: 15.999, category: "Non-métal", group: 16, period: 2, color: "#FFB2B2" },
    { symbol: "F", name: "Fluor", number: 9, atomic_mass: 18.998, category: "Non-métal", group: 17, period: 2, color: "#FFB2B2" },
    { symbol: "Ne", name: "Néon", number: 10, atomic_mass: 20.180, category: "Gaz noble", group: 18, period: 2, color: "#B2B2FF" },
    // Period 3
    { symbol: "Na", name: "Sodium", number: 11, atomic_mass: 22.990, category: "Métal alcalin", group: 1, period: 3, color: "#FFCC99" },
    { symbol: "Mg", name: "Magnésium", number: 12, atomic_mass: 24.305, category: "Métal alcalino-terreux", group: 2, period: 3, color: "#D2FF99" },
    { symbol: "Al", name: "Aluminium", number: 13, atomic_mass: 26.982, category: "Métal post-transition", group: 13, period: 3, color: "#D9B3FF" },
    { symbol: "Si", name: "Silicium", number: 14, atomic_mass: 28.085, category: "Métalloïde", group: 14, period: 3, color: "#FFD2B2" },
    { symbol: "P", name: "Phosphore", number: 15, atomic_mass: 30.974, category: "Non-métal", group: 15, period: 3, color: "#FFB2B2" },
    { symbol: "S", name: "Soufre", number: 16, atomic_mass: 32.06, category: "Non-métal", group: 16, period: 3, color: "#FFB2B2" },
    { symbol: "Cl", name: "Chlore", number: 17, atomic_mass: 35.45, category: "Non-métal", group: 17, period: 3, color: "#FFB2B2" },
    { symbol: "Ar", name: "Argon", number: 18, atomic_mass: 39.948, category: "Gaz noble", group: 18, period: 3, color: "#B2B2FF" },
    // Period 4
    { symbol: "K", name: "Potassium", number: 19, atomic_mass: 39.098, category: "Métal alcalin", group: 1, period: 4, color: "#FFCC99" },
    { symbol: "Ca", name: "Calcium", number: 20, atomic_mass: 40.078, category: "Métal alcalino-terreux", group: 2, period: 4, color: "#D2FF99" },
    { symbol: "Sc", name: "Scandium", number: 21, atomic_mass: 44.956, category: "Métal de transition", group: 3, period: 4, color: "#FFCCFF" },
    { symbol: "Ti", name: "Titane", number: 22, atomic_mass: 47.867, category: "Métal de transition", group: 4, period: 4, color: "#FFCCFF" },
    { symbol: "V", name: "Vanadium", number: 23, atomic_mass: 50.942, category: "Métal de transition", group: 5, period: 4, color: "#FFCCFF" },
    { symbol: "Cr", name: "Chrome", number: 24, atomic_mass: 51.996, category: "Métal de transition", group: 6, period: 4, color: "#FFCCFF" },
    { symbol: "Mn", name: "Manganèse", number: 25, atomic_mass: 54.938, category: "Métal de transition", group: 7, period: 4, color: "#FFCCFF" },
    { symbol: "Fe", name: "Fer", number: 26, atomic_mass: 55.845, category: "Métal de transition", group: 8, period: 4, color: "#FFCCFF" },
    { symbol: "Co", name: "Cobalt", number: 27, atomic_mass: 58.933, category: "Métal de transition", group: 9, period: 4, color: "#FFCCFF" },
    { symbol: "Ni", name: "Nickel", number: 28, atomic_mass: 58.693, category: "Métal de transition", group: 10, period: 4, color: "#FFCCFF" },
    { symbol: "Cu", name: "Cuivre", number: 29, atomic_mass: 63.546, category: "Métal de transition", group: 11, period: 4, color: "#FFCCFF" },
    { symbol: "Zn", name: "Zinc", number: 30, atomic_mass: 65.38, category: "Métal de transition", group: 12, period: 4, color: "#FFCCFF" },
    { symbol: "Ga", name: "Gallium", number: 31, atomic_mass: 69.723, category: "Métal post-transition", group: 13, period: 4, color: "#D9B3FF" },
    { symbol: "Ge", name: "Germanium", number: 32, atomic_mass: 72.63, category: "Métalloïde", group: 14, period: 4, color: "#FFD2B2" },
    { symbol: "As", name: "Arsenic", number: 33, atomic_mass: 74.922, category: "Métalloïde", group: 15, period: 4, color: "#FFD2B2" },
    { symbol: "Se", name: "Sélénium", number: 34, atomic_mass: 78.971, category: "Non-métal", group: 16, period: 4, color: "#FFB2B2" },
    { symbol: "Br", name: "Brome", number: 35, atomic_mass: 79.904, category: "Non-métal", group: 17, period: 4, color: "#FFB2B2" },
    { symbol: "Kr", name: "Krypton", number: 36, atomic_mass: 83.798, category: "Gaz noble", group: 18, period: 4, color: "#B2B2FF" },
    // Period 5
    { symbol: "Rb", name: "Rubidium", number: 37, atomic_mass: 85.468, category: "Métal alcalin", group: 1, period: 5, color: "#FFCC99" },
    { symbol: "Sr", name: "Strontium", number: 38, atomic_mass: 87.62, category: "Métal alcalino-terreux", group: 2, period: 5, color: "#D2FF99" },
    { symbol: "Y", name: "Yttrium", number: 39, atomic_mass: 88.906, category: "Métal de transition", group: 3, period: 5, color: "#FFCCFF" },
    { symbol: "Zr", name: "Zirconium", number: 40, atomic_mass: 91.224, category: "Métal de transition", group: 4, period: 5, color: "#FFCCFF" },
    { symbol: "Nb", name: "Niobium", number: 41, atomic_mass: 92.906, category: "Métal de transition", group: 5, period: 5, color: "#FFCCFF" },
    { symbol: "Mo", name: "Molybdène", number: 42, atomic_mass: 95.95, category: "Métal de transition", group: 6, period: 5, color: "#FFCCFF" },
    { symbol: "Tc", name: "Technétium", number: 43, atomic_mass: 98, category: "Métal de transition", group: 7, period: 5, color: "#FFCCFF" },
    { symbol: "Ru", name: "Ruthénium", number: 44, atomic_mass: 101.07, category: "Métal de transition", group: 8, period: 5, color: "#FFCCFF" },
    { symbol: "Rh", name: "Rhodium", number: 45, atomic_mass: 102.91, category: "Métal de transition", group: 9, period: 5, color: "#FFCCFF" },
    { symbol: "Pd", name: "Palladium", number: 46, atomic_mass: 106.42, category: "Métal de transition", group: 10, period: 5, color: "#FFCCFF" },
    { symbol: "Ag", name: "Argent", number: 47, atomic_mass: 107.87, category: "Métal de transition", group: 11, period: 5, color: "#FFCCFF" },
    { symbol: "Cd", name: "Cadmium", number: 48, atomic_mass: 112.41, category: "Métal de transition", group: 12, period: 5, color: "#FFCCFF" },
    { symbol: "In", name: "Indium", number: 49, atomic_mass: 114.82, category: "Métal post-transition", group: 13, period: 5, color: "#D9B3FF" },
    { symbol: "Sn", name: "Étain", number: 50, atomic_mass: 118.71, category: "Métal post-transition", group: 14, period: 5, color: "#D9B3FF" },
    { symbol: "Sb", name: "Antimoine", number: 51, atomic_mass: 121.76, category: "Métalloïde", group: 15, period: 5, color: "#FFD2B2" },
    { symbol: "Te", name: "Tellure", number: 52, atomic_mass: 127.6, category: "Métalloïde", group: 16, period: 5, color: "#FFD2B2" },
    { symbol: "I", name: "Iode", number: 53, atomic_mass: 126.90, category: "Non-métal", group: 17, period: 5, color: "#FFB2B2" },
    { symbol: "Xe", name: "Xénon", number: 54, atomic_mass: 131.29, category: "Gaz noble", group: 18, period: 5, color: "#B2B2FF" },
    // Period 6
    { symbol: "Cs", name: "Césium", number: 55, atomic_mass: 132.91, category: "Métal alcalin", group: 1, period: 6, color: "#FFCC99" },
    { symbol: "Ba", name: "Baryum", number: 56, atomic_mass: 137.33, category: "Métal alcalino-terreux", group: 2, period: 6, color: "#D2FF99" },
    { symbol: "La", name: "Lanthane", number: 57, atomic_mass: 138.904, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Ce", name: "Cérium", number: 58, atomic_mass: 140.116, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Pr", name: "Praséodyme", number: 59, atomic_mass: 140.907, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Nd", name: "Néodyme", number: 60, atomic_mass: 144.242, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Pm", name: "Prométhium", number: 61, atomic_mass: 145, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Sm", name: "Samarium", number: 62, atomic_mass: 150.36, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Eu", name: "Europium", number: 63, atomic_mass: 151.964, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Gd", name: "Gadolinium", number: 64, atomic_mass: 157.25, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Tb", name: "Terbium", number: 65, atomic_mass: 158.925, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Dy", name: "Dysprosium", number: 66, atomic_mass: 162.50, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Ho", name: "Holmium", number: 67, atomic_mass: 164.930, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Er", name: "Erbium", number: 68, atomic_mass: 167.259, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Tm", name: "Thulium", number: 69, atomic_mass: 168.934, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Yb", name: "Ytterbium", number: 70, atomic_mass: 173.04, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Lu", name: "Lutécium", number: 71, atomic_mass: 174.966, category: "Lanthanoïde", group: 3, period: 6, color: "#B3B3B3" },
    { symbol: "Hf", name: "Hafnium", number: 72, atomic_mass: 178.49, category: "Métal de transition", group: 4, period: 6, color: "#FFCCFF" },
    { symbol: "Ta", name: "Tantal", number: 73, atomic_mass: 180.948, category: "Métal de transition", group: 5, period: 6, color: "#FFCCFF" },
    { symbol: "W", name: "Tungstène", number: 74, atomic_mass: 183.84, category: "Métal de transition", group: 6, period: 6, color: "#FFCCFF" },
    { symbol: "Re", name: "Rhénium", number: 75, atomic_mass: 186.207, category: "Métal de transition", group: 7, period: 6, color: "#FFCCFF" },
    { symbol: "Os", name: "Osmium", number: 76, atomic_mass: 190.23, category: "Métal de transition", group: 8, period: 6, color: "#FFCCFF" },
    { symbol: "Ir", name: "Iridium", number: 77, atomic_mass: 192.217, category: "Métal de transition", group: 9, period: 6, color: "#FFCCFF" },
    { symbol: "Pt", name: "Platine", number: 78, atomic_mass: 195.084, category: "Métal de transition", group: 10, period: 6, color: "#FFCCFF" },
    { symbol: "Au", name: "Or", number: 79, atomic_mass: 196.966, category: "Métal de transition", group: 11, period: 6, color: "#FFCCFF" },
    { symbol: "Hg", name: "Mercure", number: 80, atomic_mass: 200.592, category: "Métal de transition", group: 12, period: 6, color: "#FFCCFF" },
    { symbol: "Tl", name: "Thallium", number: 81, atomic_mass: 204.38, category: "Métal post-transition", group: 13, period: 6, color: "#D9B3FF" },
    { symbol: "Pb", name: "Plomb", number: 82, atomic_mass: 207.2, category: "Métal post-transition", group: 14, period: 6, color: "#D9B3FF" },
    { symbol: "Bi", name: "Bismuth", number: 83, atomic_mass: 208.98, category: "Métal post-transition", group: 15, period: 6, color: "#D9B3FF" },
    { symbol: "Po", name: "Polonium", number: 84, atomic_mass: 209, category: "Métalloïde", group: 16, period: 6, color: "#FFD2B2" },
    { symbol: "At", name: "Astate", number: 85, atomic_mass: 210, category: "Non-métal", group: 17, period: 6, color: "#FFB2B2" },
    { symbol: "Rn", name: "Radon", number: 86, atomic_mass: 222, category: "Gaz noble", group: 18, period: 6, color: "#B2B2FF" },
    // Period 7
    { symbol: "Fr", name: "Francium", number: 87, atomic_mass: 223, category: "Métal alcalin", group: 1, period: 7, color: "#FFCC99" },
    { symbol: "Ra", name: "Radium", number: 88, atomic_mass: 226, category: "Métal alcalino-terreux", group: 2, period: 7, color: "#D2FF99" },
    { symbol: "Ac", name: "Actinium", number: 89, atomic_mass: 227, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Th", name: "Thorium", number: 90, atomic_mass: 232.038, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Pa", name: "Protactinium", number: 91, atomic_mass: 231.035, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "U", name: "Uranium", number: 92, atomic_mass: 238.028, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Np", name: "Neptunium", number: 93, atomic_mass: 237, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Pu", name: "Plutonium", number: 94, atomic_mass: 244, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Am", name: "Américium", number: 95, atomic_mass: 243, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Cm", name: "Curium", number: 96, atomic_mass: 247, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Bk", name: "Berkéllium", number: 97, atomic_mass: 247, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Cf", name: "Californium", number: 98, atomic_mass: 251, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Es", name: "Einsteinium", number: 99, atomic_mass: 252, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Fm", name: "Fermium", number: 100, atomic_mass: 257, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Md", name: "Mendelevium", number: 101, atomic_mass: 258, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "No", name: "Nobelium", number: 102, atomic_mass: 259, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Lr", name: "Lawrencium", number: 103, atomic_mass: 262, category: "Actinide", group: 3, period: 7, color: "#B3B3B3" },
    { symbol: "Rf", name: "Rutherfordium", number: 104, atomic_mass: 267, category: "Métal de transition", group: 4, period: 7, color: "#FFCCFF" },
    { symbol: "Db", name: "Dubnium", number: 105, atomic_mass: 268, category: "Métal de transition", group: 5, period: 7, color: "#FFCCFF" },
    { symbol: "Sg", name: "Seaborgium", number: 106, atomic_mass: 271, category: "Métal de transition", group: 6, period: 7, color: "#FFCCFF" },
    { symbol: "Bh", name: "Bohrium", number: 107, atomic_mass: 270, category: "Métal de transition", group: 7, period: 7, color: "#FFCCFF" },
    { symbol: "Hs", name: "Hassium", number: 108, atomic_mass: 277, category: "Métal de transition", group: 8, period: 7, color: "#FFCCFF" },
    { symbol: "Mt", name: "Meitnérium", number: 109, atomic_mass: 276, category: "Métal de transition", group: 9, period: 7, color: "#FFCCFF" },
    { symbol: "Ds", name: "Darmstadtium", number: 110, atomic_mass: 281, category: "Métal de transition", group: 10, period: 7, color: "#FFCCFF" },
    { symbol: "Rg", name: "Roentgenium", number: 111, atomic_mass: 282, category: "Métal de transition", group: 11, period: 7, color: "#FFCCFF" },
    { symbol: "Cn", name: "Copernicium", number: 112, atomic_mass: 285, category: "Métal de transition", group: 12, period: 7, color: "#FFCCFF" },
    { symbol: "Nh", name: "Nihonium", number: 113, atomic_mass: 286, category: "Métal post-transition", group: 13, period: 7, color: "#D9B3FF" },
    { symbol: "Fl", name: "Flérovium", number: 114, atomic_mass: 289, category: "Métal post-transition", group: 14, period: 7, color: "#D9B3FF" },
    { symbol: "Mc", name: "Moscovium", number: 115, atomic_mass: 288, category: "Métal post-transition", group: 15, period: 7, color: "#D9B3FF" },
    { symbol: "Lv", name: "Livermorium", number: 116, atomic_mass: 293, category: "Non-métal", group: 16, period: 7, color: "#FFB2B2" },
    { symbol: "Ts", name: "Tennessine", number: 117, atomic_mass: 294, category: "Non-métal", group: 17, period: 7, color: "#FFB2B2" },
    { symbol: "Og", name: "Oganesson", number: 118, atomic_mass: 294, category: "Gaz noble", group: 18, period: 7, color: "#B2B2FF" }
];

export default periodicTableData;